### ISSUE TITLE
本地音乐找不到音乐

### ISSUE THREAD

**Issue by sj1531122** [wzpan/wukong-contrib#99]
我按照ubuntu实际地址配置了目录并增加音乐，通过本地音乐命令，还是反馈**本地音乐目录并没有音乐文件，播放失败**

**Comment by wzpan** [comment]
试试使用绝对路径来填写地址。例如：

``` yml
## 本地音乐插件
LocalPlayer:
    path: "~/Music"  # 本地音乐存放路径
```

你需要改成：

``` yml
## 本地音乐插件
LocalPlayer:
    path: "/Users/wzpan/Music"  # 本地音乐存放路径
```
